http://localhost:4000/

###
http://localhost:4000/blockchain

###

http://localhost:3000/blocks
###
POST http://localhost:3000/blocks

{
    "data":"atasds boc"
}
###

http://localhost:4000/blocks/001639b6d16ead606a8a1a530be7d31886e18159ca4e0d5d9a1a7722a8159509

###

http://localhost:4000/balance/ad7aae05fd4b8731dff20c8d8f523a6d0b57b49b048eea5732a49c58fa3b379327350682a27667e7092d4b4b219bae618f89fc73170ea6e58479c522d2a35605

###
http://localhost:4000/balance/lynn
###
http://localhost:4000/balance/junwoo?total=true


###

POST http://localhost:4000/transaction

{
    "to":"lynn",
    "amount":10
}

###

http://localhost:4000/mempool

### 
http://localhost:4000/wallet

###
POST http://localhost:3000/peers

{
    "address" : "127.0.0.1",
    "port" : "2000"
}
###

http://localhost:4000/peers